### ISSUE TITLE
Support for USB-ISP

### ISSUE THREAD

**Issue by tpimh** [grigorig/stcgal#10]
Will stcgal support USB-ISP?

![USB-ISP](https://cloud.githubusercontent.com/assets/1071872/13954308/dc457d40-f048-11e5-9945-39f8d4ca1894.PNG)

**Comment by grigorig** [comment]
I have an STC15W4 MCU, but I haven't tried the USB mode yet, sorry.

**Comment by grigorig** [comment]
A correction: the USB-ISP mode doesn't use CDC-ACM, but raw control packets. The protocol seems to be quite simple, though. You can expect USB-ISP support, based on libusb/pyusb, to come.

**Comment by grigorig** [comment]
WIP branch: https://github.com/grigorig/stcgal/tree/usbisp

**Comment by grigorig** [comment]
The code in the branch is somewhat functional now. Flash programming works. If you are interested, please give it a go. The implementation requires pyusb.

**Comment by tpimh** [comment]
Thank you very much! I'm very interested, but unfortunately I don't have any IC supporting USB-ISP right now to test it.

**Comment by grigorig** [comment]
Setting options also works now. I'm confident this won't brick any chips, so it has been cleaned up and merged now.

**Comment by wc7086** [comment]
@grigorig Can you add this support for stc8?

![image](https://github.com/grigorig/stcgal/assets/74053663/a996f3b7-ffcd-4439-8593-d136c863c027)
