### ISSUE TITLE
Add __main__ to better work with Python Launcher

### ISSUE THREAD

**Issue by xymopen** [grigorig/stcgal#24]
Could you please make a `__main__` so I can run stcgal through `py -3 -m stcgal`?
After installed both Python 2.x and 3.x, running executable from proper version of Python will be a very tricky job. Python launcher will be the preferred way. However I can't run stcgal through Python Launcher

**Comment by grigorig** [comment]
I just pushed a commit that adds a ```__main__``` module. Please tell me if it works correctly for you.

**Comment by xymopen** [comment]
It works. Thanks!
