### ISSUE TITLE
Is it possible to flash EEPROM only?

### ISSUE THREAD

**Issue by PSLLSP** [grigorig/stcgal#26]
Is it possible to flash EEPROM memory only?

"stcgal" command is designed to have CODE and EEPROM file as parameters at command line, CODE file is the first parameter. I would like to have posibility to flash EEPROM data only.

BTW, I tried to flash STC15W201S with this tool and it worked.

**Comment by grigorig** [comment]
I think that isn't possible (by design of STC's boot loader protocol), but I have to check.

**Comment by flexifi** [comment]
any update on this

**Comment by flexifi** [comment]
Read and write EEPROM only

**Comment by PSLLSP** [comment]
You have to write your code and that should be part of your application in STC. stcgal/STC-ISP cannot read CODE or EEPROM and it cannot write only EEPROM part.
