### ISSUE TITLE
Debian package missing two build dependencies

### ISSUE THREAD

**Issue by balbirthomas** [grigorig/stcgal#32]
This is just a minor issue. The Build-Depends line in Debian/control file must also have python3-serial, python3-tqdm and python3-yaml. At least on the latest stable Debian.

**Comment by nekromant** [comment]
Thanks for reporting, will fix ASAP

**Comment by nekromant** [comment]
@grigorig I pushed a branch with fixes, I guess it's up to you to merge this to master.
