### ISSUE TITLE
publishing directly on pypi ? 

### ISSUE THREAD

**Issue by allan-simon** [grigorig/stcgal#46]
https://blog.jetbrains.com/pycharm/2017/05/how-to-publish-your-package-on-pypi/

As you can see it's not that much a burden (you create an account on pypi and you launch a simple command to push on their repo)  it will slightly easier to just do `pip install stcgal` especially when including it in bigger project

again thanks a lot for your project :)

**Comment by grigorig** [comment]
Yes, this is a good idea. I've been thinking about publishing stcgal on PyPI already and did some cleanups to setup.py a while ago. I'll try to do it in the next few days.
If I don't actually manage to do it, feel free to remind me again. :)

**Comment by allan-simon** [comment]
thanks, will do :)

**Comment by grigorig** [comment]
stcgal is on PyPI now! After some minor issues with 1.5 released yesterday, 1.6 released just now should work fine.

**Comment by allan-simon** [comment]
hurray \o/

**Comment by allan-simon** [comment]
I would put it on your readme that it is as simple as "pip install stcgal"  , as it's really a deal breaker to quickly use it,  personnaly if i see a dedicated link to "installation" i know i'm going to end up with a 10 meter long explanation on how to recompile my kernel
