### ISSUE TITLE
Doesn't support stc89c52

### ISSUE THREAD

**Issue by stan12138** [grigorig/stcgal#66]
stcgal is a great project, thank you for your work!
But when I try to use it dowmload program for stc89c52 mcu, it doesn't work.
I want know why stcgal doesn't support stc89c52, Is it possible to support stc89c52?
And my second question is how do you find the protocols for these mcu?

**Comment by nrife** [comment]
The new version of stc89c52 uses bsl7.2.5, this branch supports it

https://github.com/nrife/stcgal

**Comment by jefine** [comment]
Yes, try https://github.com/nrife/stcgal ,and you should use **-P stc89a**

**Comment by grigorig** [comment]
FWIW, I finally got my STC89C52 parts with (supposedly) new bootloader. I'll probably look at the code next weekend.

**Comment by silenceper** [comment]
@grigorig  any update?

**Comment by area-8051** [comment]
Fixed (merged nrife's patch, use stc8a protocol).
