### ISSUE TITLE
Eraseing Flash error on STC8G2K (stcgal 1.6)

### ISSUE THREAD

**Issue by banalsheep** [grigorig/stcgal#76]
Cycling power: done
Waiting for MCU: done
WARNING: Unknown model F7D4!
Target model:
  Name: UNKNOWN
  Magic: F7D4
  Code flash: 62.0 KB
  EEPROM flash: 0.0 KB
Target frequency: 11.054 MHz
Target BSL version: 7.3.12U
Target wakeup frequency: 35.400 KHz
Target ref. voltage: 1188 mV
Target mfg. date: 2021-04-15
Target options:
  reset_pin_enabled=False
  clock_gain=high
  watchdog_por_enabled=False
  watchdog_stop_idle=True
  watchdog_prescale=256
  low_voltage_reset=True
  low_voltage_threshold=0
  eeprom_erase_enabled=True
  bsl_pindetect_enabled=False
  por_reset_delay=long
  rstout_por_state=high
  uart1_remap=False
  uart2_passthrough=True
  uart2_pin_mode=push-pull
  epwm_open_drain=True
  program_eeprom_split=0
Loading flash: 311 bytes (Intel HEX)
Trimming frequency: 11.054 MHz
Switching to 19200 baud: done
Erasing flash: Serial port error: read timeout

**Comment by area-8051** [comment]
The key here might be the "Unknown model" message.
You may want to try an updated version made available here: https://github.com/area-8051/stcgal-patched
